function dipolepyrcAC = import_V_dipole_neuron(filename, dataLines)
%IMPORTFILE Import data from a text file
%  DIPOLEPYRCAC = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  DIPOLEPYRCAC = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  dipolepyrcAC = importfile("D:\users\rschoeters\Documents\Imec USEEG\dipole_pyr_cAC", [4, 5491]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 13-Nov-2019 10:49:45

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [4, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Time", "V_soma"];
opts.VariableTypes = ["double", "double"];
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
dipolepyrcAC = readtable(filename, opts);

end